nobinobi_daily_follow_up/urls.py
# -*- coding: utf-8 -*-

#      Copyright (C) 2020 <Florian Alu - Prolibre - https://prolibre.com
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU Affero General Public License as
#      published by the Free Software Foundation, either version 3 of the
#      License, or (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU Affero General Public License for more details.
#
#      You should have received a copy of the GNU Affero General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.conf.urls import url
from django.urls import path, include, register_converter
from nobinobi_core.functions import FourDigitConverter, TwoDigitConverter
from rest_framework.routers import DefaultRouter

from nobinobi_daily_follow_up import views
from nobinobi_daily_follow_up.utils import IsoDateConverter
from nobinobi_daily_follow_up.views import ClassroomJsonView

app_name = 'nobinobi_daily_follow_up'

register_converter(FourDigitConverter, 'yyyy')
register_converter(TwoDigitConverter, 'mmdd')
register_converter(IsoDateConverter, 'isodate')

router = DefaultRouter()
router.register(r'presence', views.PresenceViewSet, basename="api-presence")
router.register(r'earlytroubleshooting', views.EarlyTroubleshootingViewSet, basename="api-earlytroubleshooting")

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/presence/presence_by_weeks/<isodate:from_date>/<isodate:end_date>/', views.PresenceViewSet.as_view({
        'get': 'presence_by_weeks',
    }), name='api-presence-presence-by-weeks'),
    path('api/presence/presence_by_classroom/<isodate:date>/<int:classroom_id>/', views.PresenceClassroomDateViewSet.as_view({'get': 'list'}), name='api-presence-presence-by-classroom'),
    path('api/presence/presence_by_classroom_kindergarten/<isodate:date>/<int:classroom_id>/', views.PresenceKindergartenClassroomDateViewSet.as_view({'get': 'list'}), name='api-presence-by-classroom-kindergarten'),
    path('api/presence/presence_by_weeks_and_child/<uuid:child_pk>/<isodate:from_date>/<isodate:end_date>/',
         views.PresenceViewSet.as_view({
             'get': 'presence_by_weeks_and_child',
         }), name='api-presence-presence-by-weeks-and-child'),

    path('api/dfu/all_count/', views.dfu_live_all_notification_count, name='dfu_live_all_notification_count'),
    path('api/dfu/all_list/', views.dfu_live_all_notification_list, name='dfu_live_all_notification_list'),
    path('fields/classroom_allowed.json', ClassroomJsonView.as_view(), name="classroom_allowed_json"),

    path("daily-follow-up/", include([
        path("presence/", include([
            path("",
                 view=views.PresenceChoiceView.as_view(),
                 name='Presence_choice'
                 ),
            path("list/", include([
                path("",
                     view=views.PresenceListView.as_view(),
                     name='Presence_list'
                     ),
                path("<int:pk>/",
                     view=views.PresenceDetailListView.as_view(),
                     name='Presence_detail_list'
                     )
            ])),
            path("week-list/", include([
                path("",
                     view=views.PresenceWeekListChoiceView.as_view(),
                     name='presence_week_choice'
                     ),
                path("creche/<int:classroom_id>/",
                     view=views.PresenceWeekListView.as_view(),
                     name='presence_week_list'
                     ),
                path("creche/<int:classroom_id>/<isodate:date>/",
                     view=views.PresenceWeekListView.as_view(),
                     name='presence_week_list'
                     ),
                path("kindergarten/<int:classroom_id>/",
                     view=views.PresenceWeekKinderGartenListView.as_view(),
                     name='presence_week_kindergarten_list'
                     ),
                path("kindergarten/<int:classroom_id>/<isodate:date>/",
                     view=views.PresenceWeekKinderGartenListView.as_view(),
                     name='presence_week_kindergarten_list'
                     )
            ])),
            path("admin-week-list/", include([
                path("",
                     view=views.AdminPresenceWeekListView.as_view(),
                     name='admin_presence_week'
                     ),
            ])),

            path("<int:pk>/", include([
                path("~create/",
                     view=views.PresenceCreateView.as_view(),
                     name='Presence_create'
                     ),
                path("~create/<uuid:child_pk>/",
                     view=views.PresenceCreateView.as_view(),
                     name='Presence_create'
                     ),
                path("~departure/<int:presence_pk>/",
                     view=views.PresenceDepartureView.as_view(),
                     name='Presence_departure'
                     ),
                path("~intermediate-departure/<int:presence_pk>/",
                     view=views.PresenceIntermediateDepartureView.as_view(),
                     name='Presence_intermediate_departure'
                     ),
                #     path("",
                #          view=views.PresenceDetailView.as_view(),
                #          name='Presence_detail'),
                #     path("~delete/",
                #          view=views.PresenceDeleteView.as_view(),
                #          name='Presence_delete'),
                #     path("~update/",
                #          view=views.PresenceUpdateView.as_view(),
                #          name='Presence_update'),
            ])),
        ])),
        path("stroll/", include([
            path("",
                 view=views.StrollChoiceView.as_view(),
                 name='stroll_choice'
                 ),
            path("<int:classroom_id>/pdf",
                 view=views.StrollViewPDF.as_view(),
                 name='stroll_pdf'
                 ),
        ])),
        path("group_activity/", include([
            path("",
                 view=views.GroupActivityChoiceView.as_view(),
                 name='group_activity_choice_view'
                 ),
            path("<int:classroom_id>/",
                 view=views.GroupActivityUpdateView.as_view(),
                 name='group_activity_view'
                 ),
        ])),
        path("group_daily_follow_up/", include([
            path("",
                 view=views.GroupDailyFollowUpChoiceView.as_view(),
                 name='group_daily_follow_up_choice_view'
                 ),
            path("<int:classroom_id>/",
                 view=views.GroupDailyFollowUpUpdateView.as_view(),
                 name='group_daily_follow_up_view'
                 ),
        ])),
        path("reception/", include([
            # path("",
            #      view=views.PresenceChoiceView.as_view(),
            #      name='Presence_choice'
            #      ),
            # path("list/", include([
            #     path("",
            #          view=views.PresenceListView.as_view(),
            #          name='Presence_list'
            #          ),
            #     path("<int:pk>/",
            #          view=views.PresenceDetailListView.as_view(),
            #          name='Presence_detail_list'
            #          )
            # ]))
            # path("~create/",
            #      view=views.ReceptionCreateView.as_view(),
            #      name='Reception_create'
            #      ),
            path("<int:pk>/", include([
                # path("",
                #      view=views.PresenceDetailView.as_view(),
                #      name='Presence_detail'),
                # path("~delete/",
                #      view=views.PresenceDeleteView.as_view(),
                #      name='Presence_delete'),
                path("~update/",
                     view=views.ReceptionUpdateView.as_view(),
                     name='Reception_update'),
            ])),
        ])),
        path("meals/", include([
            # path("",
            #      view=views.PresenceChoiceView.as_view(),
            #      name='Presence_choice'
            #      ),
            # path("list/", include([
            #     path("",
            #          view=views.PresenceListView.as_view(),
            #          name='Presence_list'
            #          ),
            #     path("<int:pk>/",
            #          view=views.PresenceDetailListView.as_view(),
            #          name='Presence_detail_list'
            #          )
            # ]))
            path("~create/",
                 view=views.MealDailyFollowUpCreateView.as_view(),
                 name='MealDailyFollowUp_create'
                 ),
            path("<int:pk>/", include([
                # path("",
                #      view=views.PresenceDetailView.as_view(),
                #      name='Presence_detail'),
                # path("~delete/",
                #      view=views.PresenceDeleteView.as_view(),
                #      name='Presence_delete'),
                path("~update/",
                     view=views.MealDailyFollowUpUpdateView.as_view(),
                     name='MealDailyFollowUp_update'),
            ])),
        ])),
        path("nap/", include([
            # path("",
            #      view=views.PresenceChoiceView.as_view(),
            #      name='Presence_choice'
            #      ),
            # path("list/", include([
            #     path("",
            #          view=views.PresenceListView.as_view(),
            #          name='Presence_list'
            #          ),

nobinobi_daily_follow_up/test_utils/test_app/models.py
#      Copyright (C) 2020 <Florian Alu - Prolibre - https://prolibre.com
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU Affero General Public License as
#      published by the Free Software Foundation, either version 3 of the
#      License, or (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU Affero General Public License for more details.
#
#      You should have received a copy of the GNU Affero General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.db import models

# Put your test models here

nobinobi_daily_follow_up/templates/nobinobi_daily_follow_up/presence/presence_choice_classroom.html
<!--
  ~   Copyright (C) Prolibre Sarl 2019 <Florian Alu> <alu@prolibre.com>
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU Affero General Public License as
  ~     published by the Free Software Foundation, either version 3 of the
  ~     License and any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU Affero General Public License for more details.
  ~
  ~     You should have received a copy of the GNU Affero General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

{% extends "nobinobi_daily_follow_up/base.html" %}
{% load i18n crispy_forms_tags %}

{% block content_title %}
  {{ title }}
{% endblock %}
{% block content_card_title %}{% trans "Choice a Classroom" %}{% endblock %}
{% block content_card_body %}
  {% include "includes/messages.html" %}
  {% crispy form form.helper %}
{% endblock %}
{% block content_card_footer %}

{% endblock %}

nobinobi_daily_follow_up/templates/nobinobi_daily_follow_up/presence/presence_create.html
{% load i18n %}
{% load widget_tweaks %}
{{ form.media }}

<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h3 class="modal-title">{% trans "Create Presence" %}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.field.required %}
                    {% render_field field required="required" class="form-control" placeholder=field.label %}
                {% else %}
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="submit" class="submit-btn btn btn-primary">{% trans "Create" %}</button>
    </div>
</form>

nobinobi_daily_follow_up/templates/nobinobi_daily_follow_up/presence/presence_update.html
{% load widget_tweaks static i18n %}
{{ form.media }}

<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h3 class="modal-title">{% trans "Update presence" %}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.field.required %}
                    {% render_field field required="required" class="form-control" placeholder=field.label %}
                {% else %}
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="submit" class="submit-btn btn btn-primary">{% trans "Update" %}</button>
    </div>

</form>

nobinobi_daily_follow_up/templates/nobinobi_daily_follow_up/presence/presence_week_list.html
<!--
  ~   Copyright (C) Prolibre Sarl 2019 <Florian Alu> <alu@prolibre.com>
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU Affero General Public License as
  ~     published by the Free Software Foundation, either version 3 of the
  ~     License and any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU Affero General Public License for more details.
  ~
  ~     You should have received a copy of the GNU Affero General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->
{% extends "nobinobi_daily_follow_up/base.html" %}
{% load i18n static crispy_forms_tags replacement_classroom_tags %}

{% block title %}{{ title }} - {{ classroom }} - {{ now }}{% endblock %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/nobinobi_daily_follow_up.css' %}"/>
{% endblock %}

{% block content_title_block %}
    <h1>{{ title }}
        <small>({{ classroom }})</small>
    </h1>
    <h2>{{ now|date:"SHORT_DATE_FORMAT" }}</h2>
{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item active">{{ title }}</li>
{% endblock %}

{% block content_card %}
    <div class="card-body">
        {% include "includes/messages.html" %}
        <div class="row">
            <div class="col-md-12 table-responsive">
                <div class="btn-toolbar" style="justify-content: center;" role="toolbar" aria-label="nav_times">
                    <div class="btn-group" style="display: contents;" role="group" aria-label="nav_times">
                        <a type="button" class="btn btn-secondary"
                           href="{% url 'nobinobi_daily_follow_up:presence_week_list' classroom_id=classroom.id date=month_before.date %}"><i
                            class="fa fa-angle-double-left"></i></a>
                        <a type="button" class="btn btn-secondary"
                           href="{% url 'nobinobi_daily_follow_up:presence_week_list' classroom_id=classroom.id date=week_before.date %}"><i
                            class="fa fa-angle-left"></i></a>
                        <a type="button" class="btn btn-info"
                           href="{% url 'nobinobi_daily_follow_up:presence_week_list' classroom_id=classroom.id date=today.date %}">{{ now|date:'SHORT_DATE_FORMAT' }}</a>
                        <a type="button" class="btn btn-secondary"
                           href="{% url 'nobinobi_daily_follow_up:presence_week_list' classroom_id=classroom.id date=week_after.date %}"><i
                            class="fa fa-angle-right"></i></a>
                        <a type="button" class="btn btn-secondary"
                           href="{% url 'nobinobi_daily_follow_up:presence_week_list' classroom_id=classroom.id date=month_after.date %}"><i
                            class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>

                <table class="table table-bordered text-center" width="100%">
                    <thead class="bg-dark-gradient">
                    <tr>
                        {% for day in dict_table.values %}
                            <th class="{% if day.datetime.date == today.date %}bg-info{% endif %}"
                                colspan="{{ day.periods|length }}"
                                width="20%">{{ day.datetime|date:"SHORT_DATE_FORMAT" }}</th>
                        {% endfor %}
                    </tr>
                    <tr>
                        {% for day in dict_table.values %}
                            {% for period in day.periods.values %}
                                <th class="{% if day.datetime.date == today.date %}bg-info{% endif %}">{{ period.name }}</th>
                            {% empty %}
                                <th>&nbsp;</th>
                            {% endfor %}
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for child, day in dict_table_child.items %}
                        <tr>
                            {% for day_value in day.values %}
                                {% for period in day_value.periods.values %}
                                    {% if period.dayoff %}
                                        <td class="bg-dark-gradient">{% trans "Day off" %}</td>
                                    {% elif period.holiday %}
                                        <td class="bg-dark-gradient">{% trans "Holiday" %}</td>
                                    {% elif period.closure %}
                                        <td class="bg-dark-gradient">{% trans "Closure" %}</td>
                                    {% elif not period.status %}
                                        <td class="bg-dark-gradient">&nbsp;</td>
                                    {% else %}
                                        {% spaceless %}
                                            <td class="
                                                {% if period.absence %}
                                                bg-danger-gradient
                                                {% elif period.status == "present" %}
                                                bg-present
                                                {% elif period.status == "leave" and period.troubleshooting %}
                                                bg-troubleshooting-gradient
                                                {% elif period.status == "leave" %}
                                                bg-leave-gradient
                                                {% elif period.status == "troubleshooting" %}
                                                bg-troubleshooting
                                                {% elif period.status == "replacement_classroom" %}
                                                bg-dark-gradient
                                                {% elif period.replacement_classroom %}
                                                bg-replacement-classroom
                                                {% elif period.status == "expected" %}
                                                bg-warning-gradient
                                                {% else %}
                                                bg-gray
                                                {% endif %}
                                            ">
                                                <a style="{% if period.status == "leave" or period.status == "replacement_classroom" %}color: #FFF;{% else %}color: #000;{% endif %}"
                                                   href="
                                                    {% if day_value.datetime.date == today.date %}
                                                    {% get_replacement_classroom_id child=child date=day_value.datetime.date as current_classroom_id %}
                                                    {% url 'nobinobi_daily_follow_up:Presence_detail_list' current_classroom_id %}
                                                    {% else %}
                                                    {% url 'nobinobi_daily_follow_up:DailyFollowUp_summary_week' pk=child.id date=day_value.datetime.date %}
                                                    {% endif %}
                                                ">{{ child.usual_name }}</a>
                                                <a href="{% url 'nobinobi_child:Child_detail' pk=child.pk %}"><i
                                                    class="far fa-eye"></i></a>
                                                {% if period.birthday %}
                                                    <i class="fas fa-birthday-cake"></i>
                                                {% endif %}
                                                {% if child.childspecificneed %}
                                                    <i class='fas fa-exclamation-triangle'></i>
                                                {% endif %}
                                                {% if display_age_group_in_presence %}
                                                    <small>({{ child.age_group.name.0 }})</small> {% endif %}
                                                {% if period.absence %}
                                                    <small>({{ period.absence.type }})</small>{% endif %}</td>
                                        {% endspaceless %}

                                    {% endif %}
                                {% empty %}
                                    <td class="bg-dark-gradient">&nbsp;</td>
                                {% endfor %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="bg-dark-gradient">
                        <td colspan="1000">{% trans "Expected" %}</td>
                    </tr>
                    <tr>
                        {% for day in dict_table.values %}
                            {% for period in day.periods.values %}
                                <td class="text-center">{{ period.expected }}</td>
                            {% empty %}
                                <td>&nbsp;</td>
                            {% endfor %}
                        {% endfor %}
                    </tr>
                    <tr class="bg-dark-gradient">
                        <td colspan="1000">{% trans "Present" %}</td>
                    </tr>
                    <tr>
                        {% for day in dict_table.values %}
                            {% for period in day.periods.values %}
                                <td class="text-center">{{ period.present }}</td>
                            {% empty %}
                                <td>&nbsp;</td>
                            {% endfor %}
                        {% endfor %}
                    </tr>

                    </tfoot>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block extrajs %}
{% endblock %}